name: EAS Build

on:
  push:
    tags:
      - 'v*'
      - 'release-*'
    paths:
      - 'frontend/**'

jobs:
  build-ios:
    name: Build iOS and Submit to TestFlight
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.9.0
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Build iOS
        working-directory: frontend
        run: eas build --platform ios --profile staging --auto-submit --non-interactive --no-wait